# -*- coding: utf-8 -*-
"""Students_salary.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eoQUwtAPLdX03-Y4C5xvYHYaRBRTQ-hv

1. Importamos librerias
"""

!pip install ydata-profiling
import numpy as np
import pandas as pd
#from pandas.tools.plotting import scatter_matrix
pd.set_option('display.width', 500)
pd.set_option('display.max_columns', 100)
pd.set_option('display.notebook_repr_html', True)
import seaborn as sns
sns.set(style="whitegrid")
import warnings
warnings.filterwarnings('ignore')
import string
import math
import sys
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder
import sklearn
from IPython.core.interactiveshell import InteractiveShell
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from ydata_profiling import ProfileReport

InteractiveShell.ast_node_interactivity = "all"

df = pd.read_csv("student_salary.csv")

profile = ProfileReport(df, title="Reporte de análisis exploratorio", explorative=True)

profile.to_notebook_iframe()

# Leer archivo
df = pd.read_csv("student_salary.csv")

print(df.columns)

# Eliminar filas con valores vacios
df = df.dropna()

# Eliminar columna que no aporta información relevante
df = df.drop("student_id", axis=1)

# Separar variables independientes y variable objetivo
X = df.drop("salary_lpa", axis=1)
y = df["salary_lpa"]

# Separar en entrenamiento y prueba
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
)

# Columnas categóricas
categorical_features = ["branch", "company_type", "job_role"]

# Rellenar valores nulos en columnas categóricas
for feature in categorical_features:
    X_train[feature] = X_train[feature].fillna("Unknown")
    X_test[feature] = X_test[feature].fillna("Unknown")

# Aplicar One Hot Encoding a train y test
X_train = pd.get_dummies(X_train, columns=categorical_features, dtype=int)
X_test = pd.get_dummies(X_test, columns=categorical_features, dtype=int)

# Alinear columnas para que train y test tengan las mismas columnas
X_train, X_test = X_train.align(X_test, join="left", axis=1, fill_value=0)

# Escalamiento
sc = StandardScaler()

X_train_scaled = sc.fit_transform(X_train)
X_test_scaled = sc.transform(X_test)

print(X_train)
print(X_test)